---
language: node_js
node_js:
  - "5.3.0"
git:
  depth: 3

sudo: true

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember build -e production

before_deploy:
  - openssl aes-256-cbc -K $encrypted_89a2e6e6f2a2_key -iv $encrypted_89a2e6e6f2a2_iv -in config/id_rsa.enc -out config/id_rsa -d

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh

