---
language: node_js
node_js:
  - "5.3.0"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember build -e production

deploy:
  skip_cleanup: true
